/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.gui;

/**
 *
 * @author Shrey Patel
 */
public class GUIGUI extends javax.swing.JFrame {
        
public int r1, r2, r3, r4;
    /**
     * Creates new form GUIGUI
     */
    public GUIGUI() {
        initComponents();
        this.setTitle("Circuit Complexity");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Resistor1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Resistor2 = new javax.swing.JTextField();
        Resistor4 = new javax.swing.JTextField();
        Resistor3 = new javax.swing.JTextField();
        result = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(756, 450));
        getContentPane().setLayout(null);

        jLabel1.setText("Circuit Calculator");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 20, 81, 15);

        Resistor1.setText("0");
        Resistor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resistor1ActionPerformed(evt);
            }
        });
        getContentPane().add(Resistor1);
        Resistor1.setBounds(400, 80, 60, 30);

        jButton1.setText("Press Here");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 310, 155, 25);

        Resistor2.setText("Resistor2");
        Resistor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resistor2ActionPerformed(evt);
            }
        });
        getContentPane().add(Resistor2);
        Resistor2.setBounds(270, 80, 70, 30);

        Resistor4.setText("Resistor4");
        Resistor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resistor4ActionPerformed(evt);
            }
        });
        getContentPane().add(Resistor4);
        Resistor4.setBounds(280, 170, 60, 40);

        Resistor3.setText("Resistor3");
        Resistor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resistor3ActionPerformed(evt);
            }
        });
        getContentPane().add(Resistor3);
        Resistor3.setBounds(400, 180, 70, 30);

        result.setText("Result");
        result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultActionPerformed(evt);
            }
        });
        getContentPane().add(result);
        result.setBounds(30, 350, 640, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/gui/mit-wave-computing-circuit-design-ie_resize_md.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -50, 770, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       //String tString = Resistor1.getText();
        String t2String = Resistor2.getText();
         String t3String = Resistor3.getText();
          String t4String = Resistor4.getText();
       
       
       
       
        //int r1 = Integer.parseInt(tString);
        double r2 = Double.parseDouble(t2String);
        double r3 = Double.parseDouble(t3String);
        double r4 = Double.parseDouble(t4String);
        
     
        
        double answer = (r2/r4)*r3;
        
        
        result.setText(Double.toString(answer));
        //Resistor1.setText(Integer.toString(answer));
               
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Resistor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resistor1ActionPerformed
        
    }//GEN-LAST:event_Resistor1ActionPerformed

    private void Resistor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resistor4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Resistor4ActionPerformed

    private void Resistor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resistor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Resistor2ActionPerformed

    private void Resistor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resistor3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Resistor3ActionPerformed

    private void resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIGUI().setVisible(true);
            }
        });
    }

    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Resistor1;
    private javax.swing.JTextField Resistor2;
    private javax.swing.JTextField Resistor3;
    private javax.swing.JTextField Resistor4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField result;
    // End of variables declaration//GEN-END:variables
}

